version: '3.8'
services:

  #Apache Service
  webserver:
    hostname: apache2
    image: httpd:2.4.43
    container_name: webserver
    depends_on:
      - app
    volumes:
      - "./etc/apache2/:/etc/apache2/"
    restart: unless-stopped
    tty: true
    networks:
      - net

  #MySQL Service
  db:
    hostname: db
    container_name: db
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'db'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'db'
      MYSQL_PASSWORD: 'db'
    volumes:
      - dbdata:/var/lib/mysql/ # allows you to stop and restart the db service without losing data
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - net

  #ldap Service
  ldap:
    hostname: ldap
    container_name: ldap
    image: 'osixia/openldap:1.1.8'
    networks:
      - net

  #phpldapadmin Service
  phpldapadmin:
    hostname: phpldapadmin
    container_name: phpldapadmin
    image: 'osixia/phpldapadmin:0.9.0'
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - 8081:80
    networks:
      - net  

  #PHP Service
  app:
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on: 
      - db    
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./www:/var/www/
      - "./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
    networks:
      - net

#Docker Networks
networks:
  net:
    driver: bridge
volumes:
  dbdata:
    driver: local
